name: AniList metrics

on:
  schedule:
    - cron: "0 0 * * *"     # daily at midnight UTC
  workflow_dispatch:        # lets you trigger it manually from the Actions tab

jobs:
  anilist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Hashiruu
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 3
